# Generated by Django 5.0.1 on 2024-01-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('author_names', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('guide_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_student', models.BooleanField(default=True)),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_options', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
                ('document', models.FileField(upload_to='research_documents/')),
            ],
        ),
    ]
